<?php

namespace Database\Seeders;

use App\Models\Genre;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class GenreSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    $data = [
      ['name' => 'Action'],
      ['name' => 'Adventure'],
      ['name' => 'Biography'],
      ['name' => 'Children'],
      ['name' => 'Comedy'],
      ['name' => 'Crime'],
      ['name' => 'Drama'],
      ['name' => 'Fantasy'],
      ['name' => 'Historical'],
      ['name' => 'Horror'],
      ['name' => 'Humor'],
      ['name' => 'Literary Fiction'],
      ['name' => 'Mystery'],
      ['name' => 'Philosophy'],
      ['name' => 'Romance'],
      ['name' => 'Science Fiction'],
      ['name' => 'Self-Help'],
      ['name' => 'Thriller'],
      ['name' => 'Travel'],
      ['name' => 'Young Adult'],
      ['name' => 'Health'],
      ['name' => 'Cookbook'],
      ['name' => 'Business'],
      ['name' => 'True Crime'],
      ['name' => 'Poetry'],
      ['name' => 'Art'],
      ['name' => 'Politics'],
      ['name' => 'Religion'],
      ['name' => 'Science'],
      ['name' => 'Spirituality'],
      ['name' => 'Technology'],
      ['name' => 'Photography'],
      ['name' => 'Film'],
      ['name' => 'Sports'],
      ['name' => 'Music'],
      ['name' => 'Classics'],
      ['name' => 'Economics'],
      ['name' => 'Law'],
      ['name' => 'Education'],
      ['name' => 'Science Fiction'],
      ['name' => 'Medical'],
      ['name' => 'Psychology'],
      ['name' => 'Parenting'],
      ['name' => 'Art History'],
      ['name' => 'Design'],
      ['name' => 'Fiction'],
      ['name' => 'Non-Fiction'],
      ['name' => 'Short Stories'],
      ['name' => 'Mythology'],
      ['name' => 'Graphic Novels'],
      ['name' => 'Fantasy'],
      ['name' => 'Historical Fiction'],
      ['name' => 'War'],
      ['name' => 'Cyberpunk'],
      ['name' => 'Dystopian'],
      ['name' => 'Steampunk'],
      ['name' => 'Autobiography'],
      ['name' => 'Memoir'],
      ['name' => 'Espionage'],
      ['name' => 'LGBTQ'],
      ['name' => 'Western'],
      ['name' => 'Urban Fantasy'],
      ['name' => 'Fairy Tales'],
      ['name' => 'Magical Realism'],
      ['name' => 'Thriller'],
      ['name' => 'Detective'],
      ['name' => 'Legal Thriller'],
      ['name' => 'Psychological Thriller'],
      ['name' => 'Adventure Fiction'],
      ['name' => 'Survival'],
      ['name' => 'Spy'],
      ['name' => 'Business Fiction'],
      ['name' => 'Financial Thriller'],
      ['name' => 'Investment'],
      ['name' => 'Marketing'],
      ['name' => 'Self-Improvement'],
      ['name' => 'Motivational'],
      ['name' => 'Happiness'],
      ['name' => 'Personal Finance'],
      ['name' => 'Innovation'],
      ['name' => 'Leadership'],
      ['name' => 'Productivity'],
      ['name' => 'Health and Wellness'],
      ['name' => 'Fitness'],
      ['name' => 'Diet'],
      ['name' => 'Yoga'],
      ['name' => 'Mindfulness'],
      ['name' => 'Addiction'],
      ['name' => 'Nutrition'],
      ['name' => 'Mental Health'],
      ['name' => 'Weight Loss'],
      ['name' => 'Mindset'],
      ['name' => 'Books on Learning'],
      ['name' => 'Books on Teaching'],
      ['name' => 'College'],
      ['name' => 'History'],
      ['name' => 'Geography'],
      ['name' => 'Physics'],
      ['name' => 'Chemistry'],
      ['name' => 'Biology'],
      ['name' => 'Mathematics'],
      ['name' => 'Astronomy'],
      ['name' => 'Engineering'],
      ['name' => 'Machine Learning'],
      ['name' => 'Artificial Intelligence'],
      ['name' => 'Blockchain'],
      ['name' => 'Cryptocurrency'],
      ['name' => 'Data Science'],
      ['name' => 'Quantum Computing'],
      ['name' => 'Cloud Computing'],
      ['name' => 'Robotics'],
      ['name' => 'Gaming'],
      ['name' => 'Game Development'],
      ['name' => 'Virtual Reality'],
      ['name' => 'Augmented Reality'],
      ['name' => 'Software Development'],
      ['name' => 'Web Development'],
      ['name' => 'Mobile Development'],
      ['name' => 'Data Engineering'],
      ['name' => 'Cybersecurity'],
      ['name' => 'Networking'],
      ['name' => 'Database Management'],
      ['name' => 'Game Theory'],
    ];

    Genre::insert(array_map(function ($item) {
      return array_merge($item, [
        'created_at' => now(),
        'updated_at' => now(),
      ]);
    }, $data));
  }
}
